// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `MainOperatorDef.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.transfer.operator;

public interface _MainOperatorOperations
{
    void transferBond(com.example.transfer.dto.Bond bond, Ice.Current __current);

    com.example.transfer.dto.Bond getBond(String name, Ice.Current __current);
}
