// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `MainOperatorDef.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.transfer.operator;

public interface MainOperatorPrx extends Ice.ObjectPrx
{
    public void transferBond(com.example.transfer.dto.Bond bond);

    public void transferBond(com.example.transfer.dto.Bond bond, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_transferBond(com.example.transfer.dto.Bond bond);

    public Ice.AsyncResult begin_transferBond(com.example.transfer.dto.Bond bond, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_transferBond(com.example.transfer.dto.Bond bond, Ice.Callback __cb);

    public Ice.AsyncResult begin_transferBond(com.example.transfer.dto.Bond bond, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_transferBond(com.example.transfer.dto.Bond bond, Callback_MainOperator_transferBond __cb);

    public Ice.AsyncResult begin_transferBond(com.example.transfer.dto.Bond bond, java.util.Map<String, String> __ctx, Callback_MainOperator_transferBond __cb);

    public Ice.AsyncResult begin_transferBond(com.example.transfer.dto.Bond bond, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_transferBond(com.example.transfer.dto.Bond bond, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_transferBond(com.example.transfer.dto.Bond bond, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_transferBond(com.example.transfer.dto.Bond bond, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public void end_transferBond(Ice.AsyncResult __result);

    public com.example.transfer.dto.Bond getBond(String name);

    public com.example.transfer.dto.Bond getBond(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBond(String name);

    public Ice.AsyncResult begin_getBond(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBond(String name, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBond(String name, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBond(String name, Callback_MainOperator_getBond __cb);

    public Ice.AsyncResult begin_getBond(String name, java.util.Map<String, String> __ctx, Callback_MainOperator_getBond __cb);

    public Ice.AsyncResult begin_getBond(String name, 
                                         IceInternal.Functional_GenericCallback1<com.example.transfer.dto.Bond> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getBond(String name, 
                                         IceInternal.Functional_GenericCallback1<com.example.transfer.dto.Bond> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getBond(String name, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<com.example.transfer.dto.Bond> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getBond(String name, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<com.example.transfer.dto.Bond> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public com.example.transfer.dto.Bond end_getBond(Ice.AsyncResult __result);
}
