// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `MainOperatorDef.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.transfer.operator;

public final class MainOperatorHolder extends Ice.ObjectHolderBase<MainOperator>
{
    public
    MainOperatorHolder()
    {
    }

    public
    MainOperatorHolder(MainOperator value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof MainOperator)
        {
            value = (MainOperator)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _MainOperatorDisp.ice_staticId();
    }
}
