// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `BondDef.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.transfer.dto;

public interface _BondOperations
{
    String getName(Ice.Current __current);

    void setName(String name, Ice.Current __current);

    String getCode(Ice.Current __current);

    void setCode(String code, Ice.Current __current);
}
