// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `BondDef.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.transfer.dto;

public interface BondPrx extends Ice.ObjectPrx
{
    public String getName();

    public String getName(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getName();

    public Ice.AsyncResult begin_getName(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getName(Ice.Callback __cb);

    public Ice.AsyncResult begin_getName(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getName(Callback_Bond_getName __cb);

    public Ice.AsyncResult begin_getName(java.util.Map<String, String> __ctx, Callback_Bond_getName __cb);

    public Ice.AsyncResult begin_getName(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getName(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getName(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getName(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public String end_getName(Ice.AsyncResult __result);

    public void setName(String name);

    public void setName(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setName(String name);

    public Ice.AsyncResult begin_setName(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setName(String name, Ice.Callback __cb);

    public Ice.AsyncResult begin_setName(String name, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setName(String name, Callback_Bond_setName __cb);

    public Ice.AsyncResult begin_setName(String name, java.util.Map<String, String> __ctx, Callback_Bond_setName __cb);

    public Ice.AsyncResult begin_setName(String name, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setName(String name, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_setName(String name, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setName(String name, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_setName(Ice.AsyncResult __result);

    public String getCode();

    public String getCode(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getCode();

    public Ice.AsyncResult begin_getCode(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getCode(Ice.Callback __cb);

    public Ice.AsyncResult begin_getCode(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getCode(Callback_Bond_getCode __cb);

    public Ice.AsyncResult begin_getCode(java.util.Map<String, String> __ctx, Callback_Bond_getCode __cb);

    public Ice.AsyncResult begin_getCode(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getCode(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getCode(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getCode(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public String end_getCode(Ice.AsyncResult __result);

    public void setCode(String code);

    public void setCode(String code, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setCode(String code);

    public Ice.AsyncResult begin_setCode(String code, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setCode(String code, Ice.Callback __cb);

    public Ice.AsyncResult begin_setCode(String code, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setCode(String code, Callback_Bond_setCode __cb);

    public Ice.AsyncResult begin_setCode(String code, java.util.Map<String, String> __ctx, Callback_Bond_setCode __cb);

    public Ice.AsyncResult begin_setCode(String code, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setCode(String code, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_setCode(String code, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setCode(String code, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_setCode(Ice.AsyncResult __result);
}
