// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `BondDef.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.transfer.dto;

public final class BondPrxHolder
{
    public
    BondPrxHolder()
    {
    }

    public
    BondPrxHolder(BondPrx value)
    {
        this.value = value;
    }

    public BondPrx value;
}
